/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;


import org.apache.commons.cli.*;

public class App {

    private static final Option ARG_Prime = new Option("p", "prime", false, "Check Prime Number");
    private static final Option ARG_Perfect = new Option("x", "perfect", false, "Check Perfect Number");


    public static void main(String[] args) {

        CommandLineParser clp = new DefaultParser();

        Options options = new Options();
        options.addOption(ARG_Prime);
        options.addOption(ARG_Perfect);

        try {
            CommandLine cl = clp.parse(options, args);
//            int num = 0;
            if (cl.getArgList().isEmpty()) {
                throw new Exception("No argument passed");
            }
            int num = Integer.parseInt(cl.getArgList().get(0));
            if (cl.hasOption(ARG_Prime.getOpt())) {
                Prime p = new Prime();
                boolean c = p.isPrime(num);
                System.out.println(c);
            } else if (cl.hasOption(ARG_Perfect.getOpt())) {
                PerfectNumber pn = new PerfectNumber();
                boolean d = pn.isPerfect(num);
                System.out.println(d);
            } else {
                System.out.println("Please press p or x to continue");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
}
