/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;


import org.apache.commons.cli.*;

public class App {

    private static final Option argPrime = new Option("p", "prime", false, "Check Prime Number");
    private static final Option argPerfect = new Option("x", "perfect", false, "Check Perfect Number");


    public static void main(String[] args) {

        CommandLineParser clp = new DefaultParser();

        Options options = new Options();
        options.addOption(argPrime);
        options.addOption(argPerfect);

        try {
            CommandLine cl = clp.parse(options, args);
            if (cl.getArgList().isEmpty()) {
                throw new Exception("No argument passed");
            }

            int num = Integer.parseInt(cl.getArgList().get(0));

            String result = "";

            if (cl.hasOption(argPrime.getOpt())) {
                result = CheckNumber.isPrime(num).toString();
            } else if (cl.hasOption(argPerfect.getOpt())) {
                result = CheckNumber.isPerfect(num).toString();
            } else {
                result = "Please press p or x to continue";
            }

            System.out.println(result);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
